---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: my-deployment-github
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-service-github
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/shield-advanced-protection: "true"
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-FS-1-2-Res-2020-10
    alb.ingress.kubernetes.io/tags: Environment=demo
    alb.ingress.kubernetes.io/target-type: ip
  name: my-ingress
spec:
  ingressClassName: alb
  rules:
  - host: demo-namespace.primary-int-euwest1.products-dev.cimpress.io
    http:
      paths:
      - backend:
          service:
            name: my-service-github
            port:
              number: 80
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - demo-namespace.primary-int-euwest1.products-dev.cimpress.io
